/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dih;

import net.fellbaum.dih.handler.SimpleInteractionHandler;
import org.junit.jupiter.api.Test;

import java.util.Objects;
import java.util.function.BiFunction;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        SimpleInteractionHandler handler = new SimpleInteractionHandler();
    }
}
